server {
    listen 80;
    server_name plotra.eu www.plotra.eu dev.plotra.eu;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    http2 on;
    server_name plotra.eu www.plotra.eu;

    ssl_certificate /etc/letsencrypt/live/plotra.eu/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/plotra.eu/privkey.pem;

    root /var/www/plotra-website;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}

server {
    listen 443 ssl;
    http2 on;
    server_name dev.plotra.eu;

    ssl_certificate /etc/letsencrypt/live/plotra.eu/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/plotra.eu/privkey.pem;

    location / {
        proxy_pass http://localhost:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
